version: '3'

services:
  app:
    build: .
    image: harryest/openstep:dev
    container_name: openstep-app
    ports:
      - "443:443"
    volumes:
      - /home/ubuntu/keystore.p12:/app/keystore.p12
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://openstep.cpgoe06g6rjt.ap-northeast-2.rds.amazonaws.com:3306/openstep_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Capstoneteam01!
    networks:
      - openstep-network

networks:
  openstep-network: {}